# Generated by Molecular AI Tester

import pytest
from generated_quicksort import quicksort

def test_empty():
    arr = []
    quicksort(arr)
    assert arr == []

def test_single():
    arr = [1]
    quicksort(arr)
    assert arr == [1]

def test_sorted():
    arr = [1, 2, 3, 4, 5]
    quicksort(arr)
    assert arr == [1, 2, 3, 4, 5]

def test_reverse():
    arr = [5, 4, 3, 2, 1]
    quicksort(arr)
    assert arr == [1, 2, 3, 4, 5]

def test_duplicates():
    arr = [3, 1, 4, 1, 5, 9, 2, 6, 5]
    quicksort(arr)
    assert arr == [1, 1, 2, 3, 4, 5, 5, 6, 9]

def test_large_random():
    import random
    arr = [random.randint(0, 1000) for _ in range(100)]
    expected = sorted(arr)
    quicksort(arr)
    assert arr == expected