# Generated by Molecular AI v4.1 (async)
# Winner: Optimizer
# Sync r: 0.688
# Mode: Mock

def quicksort(arr: list, low: int = 0, high: int = None) -> None:
    """In-place quicksort with Lomuto partition."""
    if high is None:
        high = len(arr) - 1
    if low < high:
        p = _partition(arr, low, high)
        quicksort(arr, low, p - 1)
        quicksort(arr, p + 1, high)

def _partition(arr: list, low: int, high: int) -> int:
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1