# Module: auth
# Complexity: 6/10
# Generated for task: Flask REST API with JWT auth and React frontendcd C:\Users\a...
# Auto-generated by Molecular AI Dynamic Code Generation

import jwt
from datetime import datetime, timedelta
from functools import wraps
from flask import request, jsonify

class AuthManager:
    def __init__(self, secret_key):
        self.secret_key = secret_key
        self.blacklist = set()
    
    def generate_token(self, user_id, expires_hours=24):
        payload = {
            'user_id': user_id,
            'exp': datetime.utcnow() + timedelta(hours=expires_hours),
            'iat': datetime.utcnow()
        }
        return jwt.encode(payload, self.secret_key, algorithm='HS256')
    
    def verify_token(self, token):
        if token in self.blacklist:
            return None
        try:
            return jwt.decode(token, self.secret_key, algorithms=['HS256'])
        except jwt.ExpiredSignatureError:
            return None
        except jwt.InvalidTokenError:
            return None
    
    def revoke_token(self, token):
        self.blacklist.add(token)
    
    def token_required(self, f):
        @wraps(f)
        def decorated(*args, **kwargs):
            token = request.headers.get('Authorization', '').replace('Bearer ', '')
            if not token:
                return jsonify({'message': 'Token is missing'}), 401
            data = self.verify_token(token)
            if not data:
                return jsonify({'message': 'Token is invalid'}), 401
            return f(*args, **kwargs)
        return decorated