# Module: backend
# Complexity: 6/10
# Generated for task: Flask REST API with JWT auth and React frontendcd C:\Users\a...
# Auto-generated by Molecular AI Dynamic Code Generation

from flask import Flask, jsonify, request
from functools import wraps
import jwt
import datetime

app = Flask(__name__)
app.config['SECRET_KEY'] = 'your-secret-key'

# In-memory storage (replace with DB in production)
users = {}

def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = request.headers.get('Authorization')
        if not token:
            return jsonify({'message': 'Token is missing'}), 401
        try:
            data = jwt.decode(token, app.config['SECRET_KEY'], algorithms=["HS256"])
        except:
            return jsonify({'message': 'Token is invalid'}), 401
        return f(*args, **kwargs)
    return decorated

@app.route('/api/users', methods=['GET'])
@token_required
def get_users():
    return jsonify(list(users.values()))

@app.route('/api/users', methods=['POST'])
def create_user():
    data = request.get_json()
    user_id = len(users) + 1
    users[user_id] = {'id': user_id, 'name': data.get('name'), 'email': data.get('email')}
    return jsonify(users[user_id]), 201

@app.route('/api/auth/login', methods=['POST'])
def login():
    data = request.get_json()
    token = jwt.encode(
        {'user': data.get('username'), 'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=24)},
        app.config['SECRET_KEY'],
        algorithm="HS256"
    )
    return jsonify({'token': token})

if __name__ == '__main__':
    app.run(debug=True)