# Module: frontend
# Complexity: 6/10
# Generated for task: Flask REST API with JWT auth and React frontendcd C:\Users\a...
# Auto-generated by Molecular AI Dynamic Code Generation

import React, { useState, useEffect } from 'react';

function App() {
  const [users, setUsers] = useState([]);
  const [token, setToken] = useState(localStorage.getItem('token') || '');

  useEffect(() => {
    if (token) {
      fetch('/api/users', { headers: { 'Authorization': token } })
        .then(r => r.json())
        .then(data => setUsers(data));
    }
  }, [token]);

  const login = async (username, password) => {
    const res = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, password })
    });
    const data = await res.json();
    setToken(data.token);
    localStorage.setItem('token', data.token);
  };

  return (
    <div>
      <h1>User Management</h1>
      {!token && <LoginForm onLogin={login} />}
      {token && <UserList users={users} />}
    </div>
  );
}

function LoginForm({ onLogin }) {
  const [user, setUser] = useState('');
  const [pass, setPass] = useState('');
  return (
    <form onSubmit={e => { e.preventDefault(); onLogin(user, pass); }}>
      <input value={user} onChange={e => setUser(e.target.value)} placeholder="Username" />
      <input type="password" value={pass} onChange={e => setPass(e.target.value)} placeholder="Password" />
      <button type="submit">Login</button>
    </form>
  );
}

function UserList({ users }) {
  return (
    <ul>
      {users.map(u => <li key={u.id}>{u.name} ({u.email})</li>)}
    </ul>
  );
}

export default App;